### ISSUE TITLE
mailTo link opens blank page when client doesn't have default web mail client setup

### ISSUE THREAD

**Issue by UtkarshKr007** [michael-small/gatsbyTestV2#13]
Clicking on the email link in Contacts opens the default email app on phone. However on browser, if a default web mail client is not set up, then the user is simply left with a blank page. The goal is to

**Comment by michael-small** [comment]
THE GOAL IS TO WHAT???

I noticed that and wondered about it too, but thanks for documenting. I've noticed that myself on sites myself. What should we do? Is there a standard way to handle this? Could we just disable it trying to open stuff on mobile?

**Comment by UtkarshKr007** [comment]
Ah, sorry. Thought I deleted that sentence as I wasn't too sure what the goal should be. I explored a solution, using window.open functions to only open the link in certain scenarios such as when user has a mail configured, but knowing that information is outside our power. Another problem with that method was if user has pop-ups blocked then the value of the window becomes null since it never opens.

**Comment by UtkarshKr007** [comment]
I think we actually don't have to worry about this issue. On the live site and localhost the mailto link doesn't open anything if the client doesn't have a default web mail set up. The only place it opens a blank page on our admin side when editing the page .I think we should keep the feature, because I have tested it for Android and Iphones and it works as intended on both.
