### ISSUE TITLE
Fix minified React error #31 in posts CMS

### ISSUE THREAD

**Issue by michael-small** [michael-small/gatsbyTestV2#21]
> Error
> There's been an error - please open an issue on GitHub.
> 
> Opening an issue pre-populates it with the error message and debugging data.
> Please verify the information is correct and remove sensitive data if exists.
> 
> Details
> Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Mon%20Apr%2027%202020%2004%3A58%3A29%20GMT-0500%20(Central%20Daylight%20Time)&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by michael-small** [comment]
Funny enough, the Yellowcake people changed something related to the date widget in the last month...

https://github.com/thriveweb/yellowcake/commit/732a1fce67a5e712b2dc6eaa8364a39933d66c0a

Corresponding PR with notes from the issue holder: https://github.com/thriveweb/yellowcake/pull/46

I have tried setting it like that but it didn't fix it, yet.

**Comment by UtkarshKr007** [comment]
The reason for this error was due to some weird behavior by the netlify date widget . If all other existing dates throughout the collection are not a string(ex: '2020-05-23'), then the date picker outputs a date object rather than it's normal string output. Along with this, the format in config.yml for date must be surround be single quotes. 
ex: `- { label: Date / Order, name: date, widget: date, format: 'YYYY-MM-DD' }`

More detailed observance of this issue is [given here](https://github.com/netlify/netlify-cms/issues/2455).

**Comment by taskooh** [comment]
This is still not working for me. 
when I set {format: 'YYYY-MM-DD'}, the newly created markdown will be
`date: 2020-05-23
`
not wrapped with single quotation

without single quotations.
on the other hand, when I set {format: "'YYYY-MM-DD'"} (single quote in double quote), the created markdown file would be
`"'date: 2020-05-23'"
`
I cannot find the way to create markdown date field with ,single quotation only.

**Comment by michael-small** [comment]
I share your frustration. @UtkarshKr007 and I spent a lot of time making fixes here and there until we got something to finally work. I looked over the relevant pieces of what I presume is the project you are working on, [HP-2020](https://github.com/staketechnologies/HP-2020). 

First of all, the single quotes on `{format: 'YYYY-MM-DD'}` is one part of our solution that worked  for us. 

Secondly, and perhaps the most infuriating thing that we looked all over for, was consistent date formatting in all existing markdown files. We figured this out because of [a comment from @noelmace.](https://github.com/netlify/netlify-cms/issues/2455#issuecomment-512779481) 

Item by item in Noel's fix:

1. Your project looks fine from the perspective of not having other branches at the time of [this commit.](https://github.com/staketechnologies/HP-2020/commit/b3678ce1750b60884b2f80dd809e2a85fb489d77) However, you may want to clear the cache. 

1. [Your `config.yml` file as it currently stands](https://github.com/staketechnologies/HP-2020/commit/683240693edc2653a6ab6e87db1cda4c7050776d#diff-e36160419abb71f07eb8f74e9d3cc8bcR16) uses single quotes so you're all good there. Last, and most important...

1. This is what really stumped us. You need to update all of the dates in your existing markdown files to the same desired format at the same time before adding new dates through your CMS. We did this manually in [this commit](https://github.com/michael-small/Morris-MN-Public-Library/commit/3a46a081460e02ea7494f79218baed7ac809867d). I would manually change the date of all of your files like my team did, leaving single quotes around them and stripping off other UTC data that isn't 'YYYY-MM-DD'. 

Hope this helps.
