### ISSUE TITLE
Components "Invalid DOM property `class``?"

### ISSUE THREAD

**Issue by michael-small** [michael-small/gatsbyTestV2#28]
Found this while removing the background video from #6 (but this is unrelated as it happens in my master local branch). It seems to be suppressed on live.

Unless this is related to updated dependencies in the PR that addresses #6, which could someone please check against your own local master, I don't know what is up. Doesn't look like it is causing any issues, yet...

**Comment by UtkarshKr007** [comment]
Didn't realize, this issue was created. Since the change was under 10 characters, I did it during the following commit: a63e7d5c60e0f69da14d87b9b4cb5aa6ec55e210.
